### ISSUE TITLE
배포 환경/서버 환경 설정

### ISSUE THREAD

**Issue by chanwoopark9301** [codestates-seb/seb45_pre_025#7]
오후
---

- [ ] 프론트 환경 설정
- [ ] 백엔드 환경 설정
- [x] ec2 생성 및 연동
- [ ] RDS  생성 및 연동
- [ ] S3 생성 및 연동

**Comment by chanwoopark9301** [comment]
이슈) 통합 회의 결과 프론트 환경은 S3로 설정 후 테스트 해보기로 함 - 5H

**Comment by chanwoopark9301** [comment]
- ec2 생성 및 연동 완료

- ssh키 등록

- 다른 코드를 ec2 인스턴스에 git clone 하여 8080포트로 연동되는지 확인함.

**Comment by blacksg** [comment]
## Done

- 백엔드 GitHub 레포지토리 브랜치 구성
  - `main` - `dev` - `backend`
- 테스트를 위한 회원 POST 요청 샘플 코드 작성

## Todo

- EC2 인스턴스에 H2 데이터베이스 설치 및 테스트
- Docker / Jenkins를 사용한 배포 환경 개선 필요

**Comment by chanwoopark9301** [comment]
## 로컬 환경에서 RDS 연동 확인 - 찬우

-> application-server 파일 추가 및 IDE 설정 변경


![Image](https://github.com/codestates-seb/seb45_pre_025/assets/129935701/b3eede8e-fbab-450e-b9ae-1938259e8046)
